server:
  port: 9788

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5500/postgres"
    username: "postgres"
    password: "qwerty"

  jpa:
    hibernate:
      ddl-auto: "create"

kafka:
  topic:
    name: "censor"